version: "3"

services:
  db:
    image: postgres
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    env_file: .env.db.prod

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data_prod:/data
    command: redis-server --appendonly yes

  web:
    build: .
    command: gunicorn penguin.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_data_prod:/code/static
    expose:
      - 8000
    env_file: .env.web.prod
    depends_on:
      - db
      - redis

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_data_prod:/code/static
    depends_on:
      - web

volumes:
  postgres_data_prod:
  redis_data_prod:
  static_data_prod:
