version: "3"

services:
  db:
    image: postgres
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    env_file: env/production/.env.db

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data_prod:/data
    command: redis-server --appendonly yes

  web:
    build: .
    command: gunicorn penguin.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_penguin:/code/static
    ports:
      - 1337:8000
    env_file: env/production/.env.web
    depends_on:
      - db
      - redis
    networks:
      - default

  celery:
    build: .
    command: celery -A penguin worker -l info
    volumes:
      - .:/code
    depends_on:
      - web
      - db
      - redis
    env_file: env/production/.env.celery

volumes:
  postgres_data_prod:
  redis_data_prod:
  static_penguin:
    external:
      name: static_penguin

networks:
  default:
    external:
      name: shared
