# Generated by Django 3.0.7 on 2020-06-14 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='開始日時')),
                ('finish', models.DateTimeField(verbose_name='終了日時')),
            ],
            options={
                'ordering': ('start',),
            },
        ),
        migrations.CreateModel(
            name='PeriodeThemeFinalVote',
            fields=[
                ('abstractperiod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='period.AbstractPeriod')),
            ],
            options={
                'verbose_name': '統一テーマ決選投票期間',
                'verbose_name_plural': '統一テーマ決選投票期間',
            },
            bases=('period.abstractperiod',),
        ),
        migrations.CreateModel(
            name='PeriodeThemeFirstVote',
            fields=[
                ('abstractperiod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='period.AbstractPeriod')),
            ],
            options={
                'verbose_name': '統一テーマ予選投票期間',
                'verbose_name_plural': '統一テーマ予選投票期間',
            },
            bases=('period.abstractperiod',),
        ),
        migrations.CreateModel(
            name='PeriodeThemeSubmit',
            fields=[
                ('abstractperiod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='period.AbstractPeriod')),
            ],
            options={
                'verbose_name': '統一テーマ応募期間',
                'verbose_name_plural': '統一テーマ応募期間',
            },
            bases=('period.abstractperiod',),
        ),
    ]
