# Generated by Django 3.0.6 on 2020-05-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=400, unique=True, verbose_name='メールアドレス')),
                ('token', models.CharField(max_length=100, verbose_name='トークン')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='仮登録日時')),
            ],
            options={
                'verbose_name': '仮登録トークン',
                'verbose_name_plural': '仮登録トークン',
            },
        ),
    ]
