# Generated by Django 3.0.6 on 2020-05-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_usertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='email',
            field=models.EmailField(max_length=400, verbose_name='メールアドレス'),
        ),
    ]
