# Generated by Django 3.0.6 on 2020-05-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200525_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='used',
            field=models.BooleanField(default=False, verbose_name='使用済'),
        ),
    ]
