# Generated by Django 3.0.6 on 2020-05-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=15, verbose_name='タイトル'),
        ),
    ]
