# Generated by Django 3.0.6 on 2020-05-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200525_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(help_text='30 文字以内で入力してください。', max_length=30, verbose_name='タイトル'),
        ),
    ]
