# Generated by Django 3.0.6 on 2020-05-25 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('home', '0008_auto_20200525_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('email', models.EmailField(max_length=200, verbose_name='メールアドレス')),
                ('slack_ch', models.CharField(max_length=100, verbose_name='slack channel')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='authGroup')),
            ],
            options={
                'verbose_name': '部局担当',
                'verbose_name_plural': '部局担当',
            },
        ),
        migrations.CreateModel(
            name='ContactKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='種別名')),
                ('groups', models.ManyToManyField(to='home.OfficeGroup', verbose_name='管轄')),
            ],
            options={
                'verbose_name': 'お問い合わせ種別',
                'verbose_name_plural': 'お問い合わせ種別',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='表題')),
                ('body', models.CharField(max_length=400, verbose_name='本文')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ContactKind', verbose_name='お問い合わせ種別')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='入力者')),
            ],
            options={
                'verbose_name': 'お問い合わせ',
                'verbose_name_plural': 'お問い合わせ',
            },
        ),
    ]
