# Generated by Django 3.0.6 on 2020-05-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_contact_contactkind_officegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='body',
            field=models.TextField(max_length=400, verbose_name='本文'),
        ),
    ]
