# Generated by Django 3.0.6 on 2020-05-25 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200525_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactkind',
            old_name='groups',
            new_name='office_groups',
        ),
    ]
