# Generated by Django 3.0.6 on 2020-05-26 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200525_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='body',
            field=models.TextField(max_length=2000, verbose_name='本文'),
        ),
    ]
