# Generated by Django 3.0.6 on 2020-05-26 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200526_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationread',
            name='office_group',
            field=models.ForeignKey(default=1, help_text='どの担当として通知を送信するかをここで選択してください。', on_delete=django.db.models.deletion.CASCADE, to='home.OfficeGroup', verbose_name='担当'),
            preserve_default=False,
        ),
    ]
