# Generated by Django 3.0.6 on 2020-05-26 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_notificationread_office_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationread',
            name='office_group',
        ),
        migrations.AddField(
            model_name='notification',
            name='office_group',
            field=models.ForeignKey(default=1, help_text='どの担当として送信するかをここで選択してください。', on_delete=django.db.models.deletion.CASCADE, to='home.OfficeGroup', verbose_name='担当'),
            preserve_default=False,
        ),
    ]
