# Generated by Django 3.0.6 on 2020-05-29 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('home', '0016_auto_20200526_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, verbose_name='メールアドレス')),
                ('slack_ch', models.CharField(max_length=100, verbose_name='slack channel')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='authGroup')),
            ],
            options={
                'verbose_name': '部局担当情報',
                'verbose_name_plural': '部局担当情報',
            },
        ),
        migrations.RemoveField(
            model_name='contactkind',
            name='office_groups',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='office_group',
        ),
        migrations.AddField(
            model_name='contactkind',
            name='groups',
            field=models.ManyToManyField(to='auth.Group', verbose_name='管轄'),
        ),
        migrations.AddField(
            model_name='notification',
            name='group',
            field=models.ForeignKey(help_text='どの担当として送信するかをここで選択してください。', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='担当'),
        ),
        migrations.DeleteModel(
            name='OfficeGroup',
        ),
    ]
