# Generated by Django 3.0.6 on 2020-05-29 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('home', '0017_auto_20200529_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='group',
            field=models.ForeignKey(help_text='どの担当として送信するかをここで選択してください。', on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='担当'),
        ),
    ]
