# Generated by Django 3.0.6 on 2020-05-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200529_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupinfo',
            options={'ordering': ('order',), 'verbose_name': '部局担当情報', 'verbose_name_plural': '部局担当情報'},
        ),
        migrations.AddField(
            model_name='groupinfo',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
