# Generated by Django 3.0.6 on 2020-05-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20200529_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactkind',
            options={'ordering': ('order',), 'verbose_name': 'お問い合わせ種別', 'verbose_name_plural': 'お問い合わせ種別'},
        ),
        migrations.AddField(
            model_name='contactkind',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
