# Generated by Django 3.0.6 on 2020-05-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20200529_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinfo',
            name='slack_ch',
            field=models.CharField(max_length=100, unique=True, verbose_name='slack channel'),
        ),
    ]
