# Generated by Django 3.0.7 on 2020-06-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20200531_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='body',
            field=models.TextField(help_text='100 文字以内で入力してください。URL を入力すると自動的にリンクに変換されます。', max_length=100, verbose_name='本文'),
        ),
    ]
