# Generated by Django 3.0.7 on 2020-06-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20200531_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='開始')),
                ('finish', models.DateTimeField(verbose_name='終了')),
            ],
        ),
    ]
