# Generated by Django 3.0.7 on 2020-06-18 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('register', '0002_auto_20200618_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.SlugField(max_length=5, null=True, verbose_name='企画コード')),
                ('accept_id', models.SlugField(max_length=5, null=True, verbose_name='登録コード')),
                ('project_name', models.CharField(max_length=100, verbose_name='企画名')),
                ('project_name_kana', models.CharField(max_length=100, verbose_name='企画名（かな）')),
                ('group_name', models.CharField(max_length=100, verbose_name='団体名')),
                ('group_name_kana', models.CharField(max_length=100, verbose_name='団体名（かな）')),
                ('food', models.BooleanField(default=False, verbose_name='飲食物提供')),
                ('description', models.TextField(max_length=1000, verbose_name='企画内容')),
                ('note', models.TextField(help_text='車両入構・マスコミの取材がある場合は入力してください', max_length=1000, verbose_name='備考')),
                ('detail_id', models.PositiveIntegerField()),
                ('submit', models.BooleanField(default=False, verbose_name='提出')),
                ('submit_datetime', models.DateTimeField(null=True, verbose_name='提出日時')),
                ('accept', models.BooleanField(default=False, verbose_name='受理')),
                ('accept_datetime', models.DateTimeField(null=True, verbose_name='受理日時')),
                ('active', models.BooleanField(default=False, verbose_name='有効')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='企画種別')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_leader', to=settings.AUTH_USER_MODEL, verbose_name='責任者')),
                ('member', models.ManyToManyField(related_name='project_member', to=settings.AUTH_USER_MODEL, verbose_name='参加者')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='register.Registration', verbose_name='登録データ')),
            ],
            options={
                'verbose_name': '企画',
                'verbose_name_plural': '企画',
            },
        ),
    ]
