# Generated by Django 3.0.7 on 2020-06-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engeki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '自主制作演劇企画',
                'verbose_name_plural': '自主制作演劇企画',
            },
        ),
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'グラウンド企画',
                'verbose_name_plural': 'グラウンド企画',
            },
        ),
        migrations.CreateModel(
            name='Mogiten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '模擬店企画',
                'verbose_name_plural': '模擬店企画',
            },
        ),
        migrations.CreateModel(
            name='Okunai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '屋内企画',
                'verbose_name_plural': '屋内企画',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'ステージ企画',
                'verbose_name_plural': 'ステージ企画',
            },
        ),
    ]
