# Generated by Django 3.0.7 on 2020-06-12 23:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0023_periodbase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodApplication',
            fields=[
                ('periodbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.PeriodBase')),
            ],
            options={
                'verbose_name': 'テーマ案募集期間',
                'verbose_name_plural': 'テーマ案募集期間',
                'ordering': ('start',),
            },
            bases=('home.periodbase',),
        ),
        migrations.CreateModel(
            name='PeriodFinalVote',
            fields=[
                ('periodbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.PeriodBase')),
            ],
            options={
                'verbose_name': '決選投票期間',
                'verbose_name_plural': '決選投票期間',
                'ordering': ('start',),
            },
            bases=('home.periodbase',),
        ),
        migrations.CreateModel(
            name='PeriodFirstVote',
            fields=[
                ('periodbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.PeriodBase')),
            ],
            options={
                'verbose_name': '予選投票期間',
                'verbose_name_plural': '予選投票期間',
                'ordering': ('start',),
            },
            bases=('home.periodbase',),
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100, verbose_name='統一テーマ')),
                ('description', models.CharField(max_length=400, validators=[django.core.validators.MinLengthValidator(100)], verbose_name='趣意文')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='応募日時')),
                ('accepted', models.BooleanField(default=False, verbose_name='受理')),
                ('final', models.BooleanField(default=False, verbose_name='決勝進出')),
                ('writer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='応募者')),
            ],
            options={
                'verbose_name': '統一テーマ案',
                'verbose_name_plural': '統一テーマ案',
            },
        ),
        migrations.CreateModel(
            name='FirstVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eptid', models.CharField(max_length=400, unique=True, verbose_name='投票者 eptid')),
                ('vote_datetime', models.DateTimeField(auto_now_add=True, verbose_name='投票日時')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.Theme', verbose_name='投票')),
            ],
            options={
                'verbose_name': '予選投票',
                'verbose_name_plural': '予選投票',
            },
        ),
        migrations.CreateModel(
            name='FinalVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eptid', models.CharField(max_length=400, unique=True, verbose_name='投票者 eptid')),
                ('vote_datetime', models.DateTimeField(auto_now_add=True, verbose_name='投票日時')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.Theme', verbose_name='投票')),
            ],
            options={
                'verbose_name': '決戦投票',
                'verbose_name_plural': '決戦投票',
            },
        ),
    ]
