# Generated by Django 3.0.7 on 2020-06-16 00:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalVoteEptid',
            fields=[
                ('eptid', models.CharField(max_length=400, primary_key=True, serialize=False, verbose_name='eptid')),
            ],
            options={
                'verbose_name': '決選投票/EPTID',
                'verbose_name_plural': '決選投票/EPTID',
            },
        ),
        migrations.CreateModel(
            name='FirstVoteEptid',
            fields=[
                ('eptid', models.CharField(max_length=400, primary_key=True, serialize=False, verbose_name='eptid')),
            ],
            options={
                'verbose_name': '予選投票/EPTID',
                'verbose_name_plural': '予選投票/EPTID',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(help_text='1 文字以上 100 文字以下で入力してください。', max_length=100, verbose_name='統一テーマ')),
                ('description', models.TextField(help_text='100 文字以上 400 文字以下で入力してください。', max_length=400, validators=[django.core.validators.MinLengthValidator(100)], verbose_name='趣意文')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='応募日時')),
                ('first_id', models.CharField(blank=True, help_text='受理した場合のみ入力', max_length=6, null=True, verbose_name='予選コード')),
                ('final_id', models.CharField(blank=True, help_text='決選進出した場合のみ入力', max_length=6, null=True, verbose_name='決選コード')),
                ('writer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='応募者')),
            ],
            options={
                'verbose_name': '統一テーマ案',
                'verbose_name_plural': '統一テーマ案',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='FirstVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.Theme', verbose_name='統一テーマ案')),
            ],
            options={
                'verbose_name': '予選投票/投票先',
                'verbose_name_plural': '予選投票/投票先',
            },
        ),
        migrations.CreateModel(
            name='FinalVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.Theme', verbose_name='統一テーマ案')),
            ],
            options={
                'verbose_name': '決選投票/投票先',
                'verbose_name_plural': '決選投票/投票先',
            },
        ),
    ]
