# Generated by Django 3.0.7 on 2020-06-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='final',
        ),
        migrations.AddField(
            model_name='theme',
            name='final_id',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='決選コード'),
        ),
        migrations.AddField(
            model_name='theme',
            name='first_id',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='予選コード'),
        ),
    ]
