# Generated by Django 3.0.7 on 2020-06-12 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_auto_20200612_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodapplication',
            options={'ordering': ('start',), 'verbose_name': 'テーマ案募集期間', 'verbose_name_plural': 'テーマ案募集期間'},
        ),
        migrations.AlterModelOptions(
            name='periodfinalvote',
            options={'ordering': ('start',), 'verbose_name': '決選投票期間', 'verbose_name_plural': '決選投票期間'},
        ),
        migrations.AlterModelOptions(
            name='periodfirstvote',
            options={'ordering': ('start',), 'verbose_name': '予選投票期間', 'verbose_name_plural': '予選投票期間'},
        ),
    ]
