# Generated by Django 3.0.7 on 2020-06-13 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_auto_20200613_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='description',
            field=models.TextField(help_text='100 文字以上 400 文字以下で入力してください。', max_length=400, validators=[django.core.validators.MinLengthValidator(100)], verbose_name='趣意文'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='theme',
            field=models.CharField(help_text='1 文字以上 100 文字以下で入力してください。', max_length=100, verbose_name='統一テーマ'),
        ),
    ]
