# Generated by Django 3.0.7 on 2020-06-13 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0004_auto_20200613_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ('pk',), 'verbose_name': '統一テーマ案', 'verbose_name_plural': '統一テーマ案'},
        ),
    ]
